jobs:
  - name: data-cleaning
    stages:
      - name: "clean-base-tables"
        tasks:
          - name: "housing"
            params: {}

      - name: "clean-derivative-tables"
        tasks:
          - name: "housing"
            params: {}
      - name: "train-test-split"
        tasks:
          - name: "train-test"
            params:
              target: median_house_value
              test_size: 0.2

  - name: feat-engg
    stages:
      - name: "feature-pipelines"
        tasks:
          - name: "transform-features"
            params:
              outliers:
                method: mean
                drop: False
              sampling_fraction: 0.1

  - name: model-gen
    stages:
      - name: "model-creation"
        tasks:
          - name: "train-model"
            params:
              random_forest:
                random_state: 42
              rnd_search:
                param_distributions:
                  n_estimators:
                    low: 1
                    high: 200
                  max_features:
                    low: 1
                    high: 8
                n_iter: 10
                cv: 5
                scoring: "neg_mean_squared_error"
                random_state: 42
              grid_search:
                param_grid:
                  - n_estimators: [3, 10, 30]
                    max_features: [2, 4, 6, 8]
                  - bootstrap: [False]
                    n_estimators: [3, 10]
                    max_features: [2, 3, 4]
                cv: 5
                scoring: "neg_mean_squared_error"
                return_train_score: True

  - name: model-eval
    stages:
      - name: "model-predict"
        tasks:
          - name: "score-model"
            params: {}
